Repository zalando/tech-radar, pull requests merged in 2025-01, with the labels that each got.

#173 Multiline legend items
  docs/radar.js
Labels: major

#176 Release 0.11
  README.md
  docs/archive/Zalando_Tech_Radar_2016_10.pdf
  docs/archive/Zalando_Tech_Radar_2017_03.pdf
  docs/archive/Zalando_Tech_Radar_2017_07.pdf
  docs/archive/Zalando_Tech_Radar_2017_11.pdf
  docs/archive/Zalando_Tech_Radar_2018_01.pdf
  docs/archive/Zalando_Tech_Radar_2018_05.pdf
  docs/archive/Zalando_Tech_Radar_2018_09.pdf
  docs/archive/Zalando_Tech_Radar_2018_10.pdf
  docs/archive/Zalando_Tech_Radar_2019_09.pdf
  docs/archive/data/2015_12.tsv
  docs/archive/data/2016_04.tsv
  docs/archive/data/2016_10.tsv
  docs/archive/data/2017_03.tsv
  docs/archive/data/2017_07.tsv
  docs/release/radar-0.11.js
Labels: major, documentation

#177 Dependencies update 2025-01-09
  yarn.lock
Labels: dependencies

#178 Update footer to 2025
  README.md
Labels: documentation
